// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMXZ8-8pEcYA2MlprlGuZ2TzWg-IOeKGM',
    appId: '1:235077747031:web:8d078e9614a5f26c1e7e12',
    messagingSenderId: '235077747031',
    projectId: 'todoapp-c138e',
    authDomain: 'todoapp-c138e.firebaseapp.com',
    storageBucket: 'todoapp-c138e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYQaSTVTq-N7krRnooO15AD_P_nduMuEk',
    appId: '1:235077747031:android:70ce46c3f07bbdc61e7e12',
    messagingSenderId: '235077747031',
    projectId: 'todoapp-c138e',
    storageBucket: 'todoapp-c138e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAta39gXhCE754CRjppe9ZKXoQqzacV5YU',
    appId: '1:235077747031:ios:275a6a136c1cd3d11e7e12',
    messagingSenderId: '235077747031',
    projectId: 'todoapp-c138e',
    storageBucket: 'todoapp-c138e.appspot.com',
    iosBundleId: 'com.example.todofire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAta39gXhCE754CRjppe9ZKXoQqzacV5YU',
    appId: '1:235077747031:ios:275a6a136c1cd3d11e7e12',
    messagingSenderId: '235077747031',
    projectId: 'todoapp-c138e',
    storageBucket: 'todoapp-c138e.appspot.com',
    iosBundleId: 'com.example.todofire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMXZ8-8pEcYA2MlprlGuZ2TzWg-IOeKGM',
    appId: '1:235077747031:web:7ef3f0fb8ed153cd1e7e12',
    messagingSenderId: '235077747031',
    projectId: 'todoapp-c138e',
    authDomain: 'todoapp-c138e.firebaseapp.com',
    storageBucket: 'todoapp-c138e.appspot.com',
  );
}
